In [2]:
import numpy as np
import pandas as pd

# Load cleaned tickets data and prepare numeric matrix as required:
# [hours logged, billing rate, billable amount, resolution hours, CSAT score]
df = pd.read_csv('it_services_tickets_cleaned.csv')
if 'resolution_time_hours' in df.columns:
    df['resolution_time_hours'] = pd.to_numeric(df['resolution_time_hours'], errors='coerce')

numeric_cols = ['hours_logged', 'billing_rate_(usd)', 'billable_amount_usd', 'resolution_time_hours', 'csat_score']
numeric_matrix = df[numeric_cols].to_numpy(dtype=float)
print('Numeric Matrix shape:', numeric_matrix.shape)
print('Columns in order:', numeric_cols)

Numeric Matrix shape: (48123, 5)
Columns in order: ['hours_logged', 'billing_rate_(usd)', 'billable_amount_usd', 'resolution_time_hours', 'csat_score']


C:\Users\MDCOE\AppData\Local\Temp\ipykernel_18092\3914799547.py:6: DtypeWarning: Columns (0: record_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('it_services_tickets_cleaned.csv')


1. Import NumPy and print its version.

In [3]:
import numpy as np
print('NumPy Version:', np.__version__)

NumPy Version: 2.5.2


2. Make an array from the hours logged column.

In [4]:
hours = df['hours_logged'].to_numpy(dtype=float)
hours

array([  nan,  1.34,  7.  , ..., 47.  ,  2.  ,  6.5 ], shape=(48123,))

3. Print the shape, the size and the data type of that array.

In [53]:
print(hours.shape)
print(hours.size)
print(hours.dtype)

(48123,)
48123
float64


4. Make an array of the numbers 1 to 50 using arange.

In [6]:
arr_1_to_50 = np.arange(1, 51)
arr_1_to_50

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

5. Make 10 evenly spaced numbers between 0 and 100 using linspace.

In [7]:
linear_space = np.linspace(0, 100, 10)
linear_space

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

6. Make an array of 10 zeros and an array of 10 ones.

In [8]:
zeros_10 = np.zeros(10)
ones_10 = np.ones(10)
print('Zeros:', zeros_10)
print('Ones:', ones_10)

Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


7. Make a 3 by 3 array of random numbers using seed 42.

In [9]:
np.random.seed(42)
rand_3x3 = np.random.rand(3, 3)
rand_3x3

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

8. Make a 2-D array from the hours logged and billing rate columns.

In [10]:
arr_2d = df[['hours_logged', 'billing_rate_(usd)']].to_numpy(dtype=float)
arr_2d

array([[   nan,  39.45],
       [  1.34,  33.15],
       [  7.  ,  48.1 ],
       ...,
       [ 47.  ,  22.8 ],
       [  2.  , 116.76],
       [  6.5 ,  89.02]], shape=(48123, 2))

9. Print how many dimensions that 2-D array has.

In [11]:
print('Number of dimensions:', arr_2d.ndim)

Number of dimensions: 2


10. Print the first 5 values of the hours array.

In [12]:
hours[:5]

array([  nan,  1.34,  7.  , 34.63, 12.76])

11. Print the last 5 values of the hours array.

In [13]:
hours[-5:]

array([50. ,  4. , 47. ,  2. ,  6.5])

12. Print every second value from the first 20 values.

In [14]:
hours[:20:2]

array([   nan,   7.  ,  12.76,    nan,   1.66,    nan,  11.63,  28.  ,
         0.59, 253.85])

13. Reverse the array.

In [ ]:
reversed_hours = hours[::-1]
reversed_hours

array([ 6.5 ,  2.  , 47.  , ...,  7.  ,  1.34,   nan], shape=(48123,))

14. Find the sum of the hours array.

In [16]:
hours_sum = np.nansum(hours)
print('Sum of hours logged:', round(hours_sum, 2))

Sum of hours logged: 2823027.25


15. Find the mean, the minimum and the maximum of the hours array.

In [17]:
print('Mean hours:', round(np.nanmean(hours), 2))
print('Min hours:', np.nanmin(hours))
print('Max hours:', np.nanmax(hours))

Mean hours: 62.46
Min hours: -12.5
Max hours: 9888.01


16. Find the standard deviation.

In [18]:
hours_std = np.nanstd(hours)
print('Standard deviation:', round(hours_std, 2))

Standard deviation: 482.71


17. Find the median.

In [19]:
hours_median = np.nanmedian(hours)
print('Median hours:', round(hours_median, 2))

Median hours: 13.13


18. Count how many values are missing in the array.

In [20]:
missing_count = np.isnan(hours).sum()
print('Missing values in hours array:', missing_count)

Missing values in hours array: 2924


19. Find the mean while ignoring the missing values.

In [21]:
mean_ignoring_na = np.nanmean(hours)
print('Mean (ignoring NaNs):', round(mean_ignoring_na, 2))

Mean (ignoring NaNs): 62.46


20. Replace all the missing values with 0.

In [22]:
hours = np.nan_to_num(hours, nan=0.0)
print('Remaining NaNs after replacement:', np.isnan(hours).sum())

Remaining NaNs after replacement: 0


21. Count how many values are greater than 100.

In [23]:
count_gt_100 = np.sum(hours > 100)
print('Count of tickets with hours > 100:', count_gt_100)

Count of tickets with hours > 100: 1994


22. Show only the values that are greater than 100.

In [24]:
hours_gt_100 = hours[hours > 100]
print('Sample values > 100:', hours_gt_100[:10])
print('Total values > 100:', len(hours_gt_100))

Sample values > 100: [ 253.85  541.3   128.   1900.66  133.35 1291.7   373.68 5000.    723.5
  429.9 ]
Total values > 100: 1994


23. Show the values that are between 10 and 50.

In [25]:
hours_10_50 = hours[(hours >= 10) & (hours <= 50)]
print('Sample values between 10 and 50:', hours_10_50[:10])
print('Count of values between 10 and 50:', len(hours_10_50))

Sample values between 10 and 50: [34.63 12.76 15.3  11.1  11.63 28.   10.16 32.71 30.84 18.  ]
Count of values between 10 and 50: 21258


24. Count how many values are negative.

In [26]:
neg_count = np.sum(hours < 0)
print('Count of negative hour values:', neg_count)

Count of negative hour values: 185


25. Replace all the negative values with 0.

In [27]:
hours[hours < 0] = 0.0
print('Negative values remaining:', np.sum(hours < 0))

Negative values remaining: 0


26. Sort the array from smallest to largest.

In [28]:
sorted_hours = np.sort(hours)
sorted_hours

array([   0.  ,    0.  ,    0.  , ..., 8760.  , 9888.01, 9888.01],
      shape=(48123,))

27. Find the position of the largest value.

In [29]:
max_pos = np.argmax(hours)
print('Index of maximum value:', max_pos, 'with value:', hours[max_pos])

Index of maximum value: 10041 with value: 9888.01


28. Find the position of the smallest value.

In [30]:
min_pos = np.argmin(hours)
print('Index of minimum value:', min_pos, 'with value:', hours[min_pos])

Index of minimum value: 0 with value: 0.0


29. Find the 5 largest values.

In [31]:
top_5_largest = np.sort(hours)[-5:][::-1]
print('5 largest values:', top_5_largest)

5 largest values: [9888.01 9888.01 8760.   8760.   8760.  ]


30. Round every value to 1 decimal place.

In [32]:
rounded_hours = np.round(hours, 1)
rounded_hours[:10]

array([ 0. ,  1.3,  7. , 34.6, 12.8, 15.3,  0. ,  9. ,  1.7, 11.1])

31. Multiply every value by 2.

In [33]:
doubled_hours = hours * 2
doubled_hours[:10]

array([ 0.  ,  2.68, 14.  , 69.26, 25.52, 30.6 ,  0.  , 18.  ,  3.32,
       22.2 ])

32. Add 10 to every value.

In [34]:
hours_plus_10 = hours + 10
hours_plus_10[:10]

array([10.  , 11.34, 17.  , 44.63, 22.76, 25.3 , 10.  , 19.  , 11.66,
       21.1 ])

33. Multiply the hours array by the billing rate array.

In [35]:
rates = np.nan_to_num(df['billing_rate_(usd)'].to_numpy(dtype=float), nan=0.0)
effort_x_rate = hours * rates
effort_x_rate[:10]

array([   0.    ,   44.421 ,  336.7   , 1834.6974,  292.204 , 1828.35  ,
          0.    ,  432.54  ,  120.1342,  313.353 ])

34. Check whether the two arrays have the same length.

In [36]:
same_len = (len(hours) == len(rates))
print(f'Arrays have same length ({len(hours)}):', same_len)

Arrays have same length (48123): True


35. Use np.where to mark values above 24 as slow and the rest as fast.

In [37]:
speed_status = np.where(hours > 24, 'slow', 'fast')
print('Unique labels:', np.unique(speed_status, return_counts=True))
speed_status[:15]

Unique labels: (array(['fast', 'slow'], dtype='<U4'), array([33488, 14635]))


array(['fast', 'fast', 'fast', 'slow', 'fast', 'fast', 'fast', 'fast',
       'fast', 'fast', 'fast', 'fast', 'fast', 'slow', 'slow'],
      dtype='<U4')

36. Make an array of the unique priority values.

In [38]:
unique_priorities = np.unique(df['priority'].dropna().astype(str))
unique_priorities

array([' ', '1', '2', '3', '4', 'CRITICAL', 'Critical', 'HIGH', 'High',
       'LOW', 'Low', 'MEDIUM', 'Medium', 'P1', 'P1 - Critical', 'P2',
       'P3', 'P4', 'PRIORITY', 'high', 'low', 'medium', 'na', 'p1', 'p2',
       'p3', 'p4'], dtype=object)

37. Count how many times each unique priority value appears.

In [39]:
prio_vals, prio_counts = np.unique(df['priority'].dropna().astype(str), return_counts=True)
dict(zip(prio_vals, prio_counts))

{' ': np.int64(95),
 '1': np.int64(1931),
 '2': np.int64(1966),
 '3': np.int64(1934),
 '4': np.int64(1919),
 'CRITICAL': np.int64(1993),
 'Critical': np.int64(2000),
 'HIGH': np.int64(1950),
 'High': np.int64(2003),
 'LOW': np.int64(1945),
 'Low': np.int64(1840),
 'MEDIUM': np.int64(1949),
 'Medium': np.int64(1941),
 'P1': np.int64(1891),
 'P1 - Critical': np.int64(1969),
 'P2': np.int64(1907),
 'P3': np.int64(1950),
 'P4': np.int64(1880),
 'PRIORITY': np.int64(1),
 'high': np.int64(1971),
 'low': np.int64(1950),
 'medium': np.int64(2023),
 'na': np.int64(130),
 'p1': np.int64(1934),
 'p2': np.int64(1898),
 'p3': np.int64(1988),
 'p4': np.int64(1909)}

38. Take the first 100 values and reshape them into a 10 by 10 array.

In [40]:
matrix_10x10 = hours[:100].reshape(10, 10)
matrix_10x10

array([[0.00000e+00, 1.34000e+00, 7.00000e+00, 3.46300e+01, 1.27600e+01,
        1.53000e+01, 0.00000e+00, 9.00000e+00, 1.66000e+00, 1.11000e+01],
       [0.00000e+00, 1.44000e+00, 1.16300e+01, 7.23100e+01, 2.80000e+01,
        1.01600e+01, 5.90000e-01, 7.00000e+00, 2.53850e+02, 4.20000e+00],
       [5.08100e+01, 8.01000e+00, 6.79400e+01, 0.00000e+00, 3.27100e+01,
        5.41300e+02, 6.91000e+00, 3.08400e+01, 3.51000e+00, 4.34000e+00],
       [1.80000e+01, 3.14400e+01, 3.42000e+00, 2.44600e+01, 3.90000e+01,
        1.30000e+01, 3.00200e+01, 1.15100e+01, 6.30200e+01, 1.03000e+00],
       [2.90000e+00, 3.92000e+00, 2.02200e+01, 2.41500e+01, 8.40000e+01,
        0.00000e+00, 2.70000e+01, 5.20000e+00, 4.00000e+00, 2.76000e+00],
       [1.12600e+01, 2.40000e+01, 5.26000e+00, 1.40000e+01, 5.00000e+00,
        1.14100e+01, 0.00000e+00, 1.80000e+01, 1.28000e+02, 1.54000e+01],
       [1.90066e+03, 4.00000e+00, 3.00000e+00, 9.00000e+00, 1.33350e+02,
        1.29170e+03, 4.00000e+00, 0.00000e+00

39. Transpose that 10 by 10 array.

In [41]:
transposed_matrix = matrix_10x10.T
transposed_matrix

array([[0.00000e+00, 0.00000e+00, 5.08100e+01, 1.80000e+01, 2.90000e+00,
        1.12600e+01, 1.90066e+03, 2.05100e+01, 1.91700e+01, 1.30000e+01],
       [1.34000e+00, 1.44000e+00, 8.01000e+00, 3.14400e+01, 3.92000e+00,
        2.40000e+01, 4.00000e+00, 1.13300e+01, 1.78600e+01, 1.09100e+01],
       [7.00000e+00, 1.16300e+01, 6.79400e+01, 3.42000e+00, 2.02200e+01,
        5.26000e+00, 3.00000e+00, 5.99100e+01, 9.21000e+00, 8.00000e+00],
       [3.46300e+01, 7.23100e+01, 0.00000e+00, 2.44600e+01, 2.41500e+01,
        1.40000e+01, 9.00000e+00, 1.00000e+00, 5.40000e+01, 3.81000e+00],
       [1.27600e+01, 2.80000e+01, 3.27100e+01, 3.90000e+01, 8.40000e+01,
        5.00000e+00, 1.33350e+02, 2.29700e+01, 0.00000e+00, 3.73680e+02],
       [1.53000e+01, 1.01600e+01, 5.41300e+02, 1.30000e+01, 0.00000e+00,
        1.14100e+01, 1.29170e+03, 0.00000e+00, 2.00000e+01, 1.13800e+01],
       [0.00000e+00, 5.90000e-01, 6.91000e+00, 3.00200e+01, 2.70000e+01,
        0.00000e+00, 4.00000e+00, 2.49000e+01

40. Flatten it back into a 1-D array.

In [42]:
flattened_arr = transposed_matrix.flatten()
print('Flattened shape:', flattened_arr.shape)
flattened_arr[:10]

Flattened shape: (100,)


array([   0.  ,    0.  ,   50.81,   18.  ,    2.9 ,   11.26, 1900.66,
         20.51,   19.17,   13.  ])

41. Join two arrays together using np.concatenate.

In [43]:
head_10 = hours[:10]
tail_10 = hours[-10:]
joined_arr = np.concatenate([head_10, tail_10])
print('Joined array length:', len(joined_arr))
joined_arr

Joined array length: 20


array([ 0.  ,  1.34,  7.  , 34.63, 12.76, 15.3 ,  0.  ,  9.  ,  1.66,
       11.1 ,  0.  , 37.16, 19.  , 25.23,  7.21, 50.  ,  4.  , 47.  ,
        2.  ,  6.5 ])

42. Split an array into 5 equal parts.

In [44]:
split_parts = np.split(hours[:100], 5)
print('Number of splits:', len(split_parts))
print('Shape of each split:', [p.shape for p in split_parts])

Number of splits: 5
Shape of each split: [(20,), (20,), (20,), (20,), (20,)]


43. Find the 25th, 50th and 75th percentile.

In [45]:
p25, p50, p75 = np.percentile(hours, [25, 50, 75])
print(f'25th Percentile (Q1): {p25:.2f}')
print(f'50th Percentile (Median): {p50:.2f}')
print(f'75th Percentile (Q3): {p75:.2f}')

25th Percentile (Q1): 3.40
50th Percentile (Median): 11.58
75th Percentile (Q3): 28.30


44. Find the cumulative sum of the first 20 values.

In [46]:
cum_sum_20 = np.cumsum(hours[:20])
cum_sum_20

array([  0.  ,   1.34,   8.34,  42.97,  55.73,  71.03,  71.03,  80.03,
        81.69,  92.79,  92.79,  94.23, 105.86, 178.17, 206.17, 216.33,
       216.92, 223.92, 477.77, 481.97])

45. Find the difference between each value and the one before it using np.diff.

In [47]:
differences = np.diff(hours[:20])
print('Length of differences:', len(differences))
differences

Length of differences: 19


array([   1.34,    5.66,   27.63,  -21.87,    2.54,  -15.3 ,    9.  ,
         -7.34,    9.44,  -11.1 ,    1.44,   10.19,   60.68,  -44.31,
        -17.84,   -9.57,    6.41,  246.85, -249.65])

46. Keep every value inside the range 0 to 100 using np.clip.

In [48]:
clipped_hours = np.clip(hours, 0, 100)
print('Clipped min:', clipped_hours.min(), 'Clipped max:', clipped_hours.max())
clipped_hours[:10]

Clipped min: 0.0 Clipped max: 100.0


array([ 0.  ,  1.34,  7.  , 34.63, 12.76, 15.3 ,  0.  ,  9.  ,  1.66,
       11.1 ])

47. Convert the array to whole numbers.

In [49]:
hours_int = hours.astype(int)
print('Data type:', hours_int.dtype)
hours_int[:10]

Data type: int64


array([ 0,  1,  7, 34, 12, 15,  0,  9,  1, 11])

48. Copy the array, change one value in the copy, and show that the original did not change.

In [50]:
hours_copy = hours.copy()
hours_copy[0] = 888888.0
print('Copy value at index 0:', hours_copy[0])
print('Original value at index 0:', hours[0])
print('Verification - Original remains unchanged:', hours[0] != hours_copy[0])

Copy value at index 0: 888888.0
Original value at index 0: 0.0
Verification - Original remains unchanged: True


49. Save the array to a .npy file and load it back.

In [51]:
np.save('hours_array.npy', hours)
loaded_hours = np.load('hours_array.npy')
print('Saved and loaded successfully!')
print('Loaded array matches original:', np.array_equal(hours, loaded_hours))

Saved and loaded successfully!
Loaded array matches original: True


50. Find the total revenue using np.dot on the hours array and the rate array.

In [52]:
total_revenue = np.dot(hours, rates)
print(f'Total Revenue calculated via np.dot: ${total_revenue:,.2f}')

Total Revenue calculated via np.dot: $293,356,392.44
